import {createIntroCharacter} from './intro-character.mjs';
import {batchRigid} from './batch.mjs';
export async function createLobbyScene(T,loadAsset,{authored=null,loadIntro=null}={}){
 const scene=new T.Scene();scene.background=new T.Color('#0b1014');scene.fog=new T.FogExp2('#101216',.018);
 const camera=new T.PerspectiveCamera(52,16/9,.05,70);camera.position.set(0,1.64,-4.9);camera.lookAt(0,1.64,3);
 const templates=new Map();let disposed=false,visualTime=0,intro=null,introError=null;
 function release(){intro?.dispose();authored?.userData.release?.();const gs=new Set(),ms=new Set(),ts=new Set();const visit=o=>{if(o.userData.sharedRoomResource)return;if(o.geometry)gs.add(o.geometry);for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[]){ms.add(m);for(const t of Object.values(m))if(t?.isTexture)ts.add(t);}};scene.traverse(visit);for(const root of templates.values())root.traverse(visit);gs.forEach(g=>g.dispose());ts.forEach(t=>t.dispose());ms.forEach(m=>m.dispose());templates.clear();scene.clear();}
 async function place(name,p=[0,0,0],r=0){try{if(!templates.has(name)){const template=await loadAsset(name);template.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=!/wall|wing|ceiling/.test(o.name);}});templates.set(name,name==='claw'?template:batchRigid(T,template));}}catch(e){release();throw e;}const root=templates.get(name).clone(true);root.position.set(...p);root.rotation.y=r;scene.add(root);return root;}
 let left,right;
 if(authored){scene.add(authored);left=authored.getObjectByName('door-left');right=authored.getObjectByName('door-right');}
 else{await place('architecture');await place('fixtures');left=await place('door-left',[-.7,0,-2.96]);right=await place('door-right',[.7,0,-2.96]);
 await place('seating',[-3.3,0,4.6],Math.PI);await place('seating',[3.3,0,4.6],Math.PI);await place('reception',[-4.5,0,2.3],.15);}
 if(loadIntro){try{intro=await createIntroCharacter(T,loadIntro);scene.add(intro.root);}catch(error){introError=error.message;}}
 const claws=[];if(!intro)for(const side of [-1,1]){const asset=await place('claw');const root=new T.Group();root.name='outside-claw-'+side;scene.add(root);root.add(asset);root.rotation.y=Math.PI;root.scale.x=-side;const fingers=[];for(let i=0;i<4;i++){const pivot=new T.Group();pivot.position.y=i*.12;pivot.scale.x=[.8,1,.94,.73][i];root.add(pivot);for(const prefix of ['finger-','tip-']){const part=root.getObjectByName(prefix+i);if(part){pivot.add(part);part.position.y-=i*.12;}}fingers.push(pivot);}claws.push({root,side,fingers});}
 scene.add(new T.HemisphereLight('#8a9eae','#352215',.5));const key=new T.SpotLight('#ffdfb5',100,20,Math.PI/3,.55,2);key.position.set(0,4,1);key.target.position.set(0,1.5,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.bias=-.003;key.shadow.normalBias=.035;scene.add(key,key.target);
 for(const x of [-4.6,-2.4,2.4,4.6]){const light=new T.PointLight('#ffd499',6,5,2);light.position.set(x,2.4,-2.1);scene.add(light);}
 for(const x of [-3,3]){const fill=new T.PointLight('#ffdfb5',18,10,2);fill.position.set(x,3.2,5.5);scene.add(fill);}
 const car=new T.PointLight('#afc6cb',8,5,2);car.position.set(0,2.7,-4.5);scene.add(car);
 return{scene,camera,inspect:()=>({asset:authored?.userData.roomAsset??null,doorPositions:[left.position.x,right.position.x],intro:intro?.inspect()??{asset:null,fallback:true,error:introError}}),resize(w,h){if(w<=0||h<=0||!Number.isFinite(w/h))return;camera.aspect=w/h;camera.fov=w/h<1.2?68:52;camera.position.z=-4.9;camera.updateProjectionMatrix();},update(s,settings={},dt=0){if(disposed)return;visualTime+=Math.max(0,dt);authored?.userData.updateRoom?.(visualTime,settings);intro?.update(s,settings);const shake=settings.reducedMotion||settings.softScares?0:s.shudder;left.position.x=-.7-s.openness*1.4+shake;right.position.x=.7+s.openness*1.4-shake;for(const {root,side,fingers} of claws){root.visible=!settings.softScares&&s.claws>0;root.position.set(side*(s.openness*1.4+.006),1.45,-2.8-.28*s.claws);fingers.forEach((p,i)=>p.rotation.z=side*Math.sin(s.stageTime*2.2+i)*.025*s.strain);}car.intensity=2;},dispose(){if(disposed)return;disposed=true;key.shadow.map?.dispose();release();}};
}
